name: Check pull request
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm run lint
